--- 
- 
  apt: name={{ item }} state=present force=yes
  name: Install MySQL database
  with_items: 
    - mysql-server
    - mysql-client
- 
  name: Start Mysql Service
  shell: service mysql start
- 
  mysql_db: name={{ db_name }} state=present
  name: Create Application Database
- 
  mysql_user: name={{ db_user }} password={{ db_password }} priv='*.*:ALL' host='%' state='present'
  name: Create Application DB User
